### ISSUE TITLE
Slides de présentation

### ISSUE THREAD

**Issue by anpar** [anpar/1243#94]
## TODO
- [ ] Introduction : pour qui?
- [x] Tache 3 : @sschrurs et @NGillain ;
- [x] Tache 8 : @PaulinePiraux et @anpar ;
- [ ] Conclusion tache 3 et 8 : @sschrurs @NGillain @PaulinePiraux @anpar ;
- [ ] Bilan de groupe et conclusion général du projet : tout le monde ;
- [ ] Sources pour les tâches 3 et 8 : 
  @PaulinePiraux : ajouter toutes tes sources dans sources-tache8.bib et ajoute les \cite{label} dans les slides.
  @NGillain : ajouter les cite{label} dans tes slides ;
